import jsPDF from "jspdf";

export type BookingPdfData = {
  businessName: string; clientName: string; eventType: string; eventDate: string; eventTime: string;
  durationMinutes: number; venueSpace: string; guestCount: number; menuSummary: string[];
  dietaryRequirements?: string | null; allergies?: string | null; totalAmount: number;
  depositAmount: number; depositDueDate?: string | null; balanceDueDate?: string | null; terms?: string | null;
};

const money = (value: number) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(value);

export function buildBookingConfirmationPdf(data: BookingPdfData) {
  const doc = new jsPDF();
  const gold: [number, number, number] = [172, 132, 93];
  doc.setFillColor(18, 16, 15); doc.rect(0, 0, 210, 45, "F");
  doc.setTextColor(245, 245, 245); doc.setFont("times", "bold"); doc.setFontSize(24);
  doc.text(data.businessName, 18, 23);
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(...gold);
  doc.text("BOOKING CONFIRMATION", 18, 34);

  let y = 60;
  doc.setTextColor(25, 25, 25); doc.setFont("times", "bold"); doc.setFontSize(18);
  doc.text(data.clientName, 18, y); y += 10;
  doc.setDrawColor(...gold); doc.line(18, y, 192, y); y += 12;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  const rows = [
    ["Event", data.eventType], ["Date", data.eventDate], ["Time", data.eventTime],
    ["Duration", `${data.durationMinutes} minutes`], ["Venue", data.venueSpace], ["Guests", String(data.guestCount)],
  ];
  rows.forEach(([label, value]) => { doc.setFont("helvetica", "bold"); doc.text(label, 18, y); doc.setFont("helvetica", "normal"); doc.text(value, 65, y); y += 8; });
  y += 6; doc.setFont("times", "bold"); doc.setFontSize(15); doc.text("Menu & catering", 18, y); y += 9;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  (data.menuSummary.length ? data.menuSummary : ["Menu to be confirmed"]).forEach((item) => { doc.text(`• ${item}`, 22, y); y += 7; });
  if (data.dietaryRequirements) { doc.setFont("helvetica", "bold"); doc.text("Dietary requirements", 18, y); doc.setFont("helvetica", "normal"); y += 6; doc.text(doc.splitTextToSize(data.dietaryRequirements, 170), 18, y); y += 12; }
  if (data.allergies) { doc.setTextColor(170, 40, 40); doc.setFont("helvetica", "bold"); doc.text(`ALLERGIES: ${data.allergies}`, 18, y); doc.setTextColor(25, 25, 25); y += 10; }
  doc.setFont("times", "bold"); doc.setFontSize(15); doc.text("Payment summary", 18, y); y += 9;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  [["Estimated total", money(data.totalAmount)], ["Deposit", money(data.depositAmount)], ["Deposit due", data.depositDueDate || "—"], ["Balance due", data.balanceDueDate || "—"]].forEach(([label, value]) => { doc.setFont("helvetica", "bold"); doc.text(label, 18, y); doc.setFont("helvetica", "normal"); doc.text(value, 65, y); y += 8; });
  if (data.terms) { y += 6; doc.setFont("times", "bold"); doc.setFontSize(13); doc.text("Terms", 18, y); y += 7; doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.text(doc.splitTextToSize(data.terms, 174), 18, y); }
  doc.setFontSize(8); doc.setTextColor(110, 110, 110); doc.text("Generated by Regal Clock", 18, 286);
  return doc;
}