import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { getCaller, hasBusinessRole, serviceClient } from "../_shared/auth.ts";

const schema = z.object({ bookingId: z.string().uuid(), appUrl: z.string().url() });
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" }[char] ?? char));
async function hash(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");}

serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
  try{
    const parsed=schema.safeParse(await req.json());if(!parsed.success)return new Response(JSON.stringify({error:"Invalid request"}),{status:400,headers:{...corsHeaders,"Content-Type":"application/json"}});
    const admin=serviceClient();const caller=await getCaller(req,admin);if(!caller)return new Response(JSON.stringify({error:"Unauthorized"}),{status:401,headers:{...corsHeaders,"Content-Type":"application/json"}});
    const{data:booking}=await admin.from("crm_bookings").select("id,business_id,event_date,start_time,venue_space,guest_count,deposit_amount,crm_leads(full_name,email,event_type),businesses(name)").eq("id",parsed.data.bookingId).single();
    if(!booking||!hasBusinessRole(caller,booking.business_id,["admin","super_admin","sales_marketing_manager"]))return new Response(JSON.stringify({error:"Forbidden"}),{status:403,headers:{...corsHeaders,"Content-Type":"application/json"}});
    const lead=booking.crm_leads as unknown as {full_name:string;email:string|null;event_type:string};const business=booking.businesses as unknown as {name:string};if(!lead?.email)return new Response(JSON.stringify({error:"The lead does not have an email address"}),{status:400,headers:{...corsHeaders,"Content-Type":"application/json"}});
    const token=crypto.randomUUID()+crypto.randomUUID();await admin.from("crm_confirmation_tokens").delete().eq("booking_id",booking.id);await admin.from("crm_confirmation_tokens").insert({business_id:booking.business_id,booking_id:booking.id,token_hash:await hash(token),expires_at:new Date(Date.now()+14*86400000).toISOString()});
    const link=`${parsed.data.appUrl.replace(/\/$/,"")}/booking/confirm/${encodeURIComponent(token)}`;const resend=Deno.env.get("RESEND_API_KEY");if(!resend)throw new Error("Email service is not configured");
    const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resend}`,"Content-Type":"application/json"},body:JSON.stringify({from:"Regal Clock <noreply@omnexventures.com>",to:[lead.email],subject:`Please confirm your ${business.name} booking`,html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#1a1a1a"><div style="background:#12100f;padding:28px;color:#fff"><h1 style="margin:0;color:#ac845d">${escapeHtml(business.name)}</h1><p style="margin:8px 0 0">Booking confirmation</p></div><div style="padding:28px;border:1px solid #ddd"><p>Dear ${escapeHtml(lead.full_name)},</p><p>Please review and confirm your ${escapeHtml(lead.event_type)} booking.</p><table style="width:100%;margin:20px 0;border-collapse:collapse"><tr><td style="padding:8px;border-bottom:1px solid #ddd">Date</td><td style="padding:8px;border-bottom:1px solid #ddd"><strong>${escapeHtml(booking.event_date)}</strong></td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Time</td><td style="padding:8px;border-bottom:1px solid #ddd"><strong>${escapeHtml(booking.start_time)}</strong></td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Venue</td><td style="padding:8px;border-bottom:1px solid #ddd"><strong>${escapeHtml(booking.venue_space)}</strong></td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Guests</td><td style="padding:8px;border-bottom:1px solid #ddd"><strong>${booking.guest_count}</strong></td></tr></table><a href="${link}" style="display:inline-block;background:#ac845d;color:#12100f;padding:12px 20px;text-decoration:none;font-weight:bold">Review and confirm</a><p style="font-size:12px;color:#666;margin-top:20px">This secure link expires in 14 days.</p></div></div>`})});
    if(!response.ok){const detail=await response.text();console.error(`Email provider failed [${response.status}]: ${detail}`);return new Response(JSON.stringify({error:"Email provider failed",status:response.status,details:detail}),{status:response.status,headers:{...corsHeaders,"Content-Type":"application/json"}});}
    await admin.from("crm_bookings").update({confirmation_sent_at:new Date().toISOString(),status:"sent"}).eq("id",booking.id);return new Response(JSON.stringify({ok:true}),{headers:{...corsHeaders,"Content-Type":"application/json"}});
  }catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:"Unable to send confirmation"}),{status:500,headers:{...corsHeaders,"Content-Type":"application/json"}});}
});