import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, RefreshCw } from "lucide-react";
import { format } from "date-fns";
import { buildInvoicePdf } from "@/lib/invoicePdf";
import { getBillTo } from "@/lib/invoiceBillTo";
import { useToast } from "@/hooks/use-toast";

interface Props {
  employeeCode: string | null;
  businessCode: string | null;
}

interface InvoiceRow {
  id: string;
  invoice_number: number;
  invoice_code: string;
  week_start: string;
  week_end: string;
  issue_date: string;
  due_date: string;
  net_hours: number;
  hourly_rate: number;
  amount: number;
  employee_name: string;
  employee_abn: string | null;
  account_name: string | null;
  bsb: string | null;
  account_number: string | null;
  business_name: string;
  business_code: string;
}

const invoiceNumberDisplay = (bizCode: string, weekEnd: Date, n: number) =>
  `${(bizCode || "").toUpperCase()}-${format(weekEnd, "yyyy")}-${String(n).padStart(4, "0")}`;

export default function EmployeeInvoicesSection({ employeeCode, businessCode }: Props) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState<InvoiceRow[]>([]);

  const load = async () => {
    if (!employeeCode || !businessCode) return;
    setLoading(true);
    const { data, error } = await supabase.rpc("get_employee_invoices", {
      _employee_code: employeeCode,
      _business_code: businessCode,
    });
    if (error) {
      toast({ title: "Could not load invoices", description: error.message, variant: "destructive" });
    }
    setRows((data as InvoiceRow[]) || []);
    setLoading(false);
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [employeeCode, businessCode]);

  const download = (row: InvoiceRow) => {
    const weekStart = new Date(row.week_start + "T00:00:00");
    const weekEnd = new Date(row.week_end + "T00:00:00");
    const issue = new Date(row.issue_date + "T00:00:00");
    const due = new Date(row.due_date + "T00:00:00");
    const billTo = getBillTo(row.business_code, row.business_name);
    const doc = buildInvoicePdf({
      invoice_number: row.invoice_number,
      invoice_number_display: invoiceNumberDisplay(row.business_code, weekEnd, row.invoice_number),
      invoice_code: row.invoice_code,
      week_start: weekStart,
      week_end: weekEnd,
      issue_date: issue,
      due_date: due,
      net_hours: Number(row.net_hours),
      hourly_rate: Number(row.hourly_rate),
      amount: Number(row.amount),
      employee: {
        name: row.employee_name,
        abn: row.employee_abn,
        account_name: row.account_name,
        bsb: row.bsb,
        account_number: row.account_number,
      },
      billTo,
    });
    const safeName = row.employee_name.replace(/\s+/g, "_");
    doc.save(`Invoice_${safeName}_${row.invoice_code}_${format(weekStart, "dd.MM.yyyy")}.pdf`);
  };

  const view = (row: InvoiceRow) => {
    const weekStart = new Date(row.week_start + "T00:00:00");
    const weekEnd = new Date(row.week_end + "T00:00:00");
    const issue = new Date(row.issue_date + "T00:00:00");
    const due = new Date(row.due_date + "T00:00:00");
    const billTo = getBillTo(row.business_code, row.business_name);
    const doc = buildInvoicePdf({
      invoice_number: row.invoice_number,
      invoice_number_display: invoiceNumberDisplay(row.business_code, weekEnd, row.invoice_number),
      invoice_code: row.invoice_code,
      week_start: weekStart,
      week_end: weekEnd,
      issue_date: issue,
      due_date: due,
      net_hours: Number(row.net_hours),
      hourly_rate: Number(row.hourly_rate),
      amount: Number(row.amount),
      employee: {
        name: row.employee_name,
        abn: row.employee_abn,
        account_name: row.account_name,
        bsb: row.bsb,
        account_number: row.account_number,
      },
      billTo,
    });
    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank", "noopener,noreferrer");
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          Invoices generated by your business admin appear here. Tap to view or download.
        </p>
        <Button variant="ghost" size="sm" onClick={load} disabled={loading}>
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
        </Button>
      </div>

      {loading ? (
        <Card><CardContent className="p-6 text-center text-xs text-muted-foreground">Loading invoices…</CardContent></Card>
      ) : rows.length === 0 ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">
            <FileText className="h-8 w-8 mx-auto mb-2 opacity-50" />
            <p className="text-sm">No invoices yet.</p>
            <p className="text-xs mt-1">Your weekly invoices will appear here once generated.</p>
          </CardContent>
        </Card>
      ) : (
        rows.map((row) => {
          const weekStart = new Date(row.week_start + "T00:00:00");
          const weekEnd = new Date(row.week_end + "T00:00:00");
          const issue = new Date(row.issue_date + "T00:00:00");
          const due = new Date(row.due_date + "T00:00:00");
          return (
            <Card key={row.id}>
              <CardHeader className="pb-2 px-4 pt-3">
                <div className="flex items-center justify-between gap-2">
                  <CardTitle className="text-sm font-medium text-foreground flex items-center gap-2">
                    <FileText className="h-4 w-4 text-primary" />
                    {invoiceNumberDisplay(row.business_code, weekEnd, row.invoice_number)}
                  </CardTitle>
                  <Badge variant="outline" className="font-mono text-xs">${Number(row.amount).toFixed(2)}</Badge>
                </div>
              </CardHeader>
              <CardContent className="px-4 pb-3 space-y-2">
                <div className="grid grid-cols-2 gap-x-3 gap-y-1 text-xs">
                  <div>
                    <span className="text-muted-foreground">Week: </span>
                    <span className="text-foreground">{format(weekStart, "dd MMM")} – {format(weekEnd, "dd MMM yyyy")}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Code: </span>
                    <span className="font-mono text-foreground">{row.invoice_code}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Issued: </span>
                    <span className="text-foreground">{format(issue, "dd/MM/yyyy")}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Due: </span>
                    <span className="text-foreground">{format(due, "dd/MM/yyyy")}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Hours: </span>
                    <span className="font-mono text-foreground">{Number(row.net_hours).toFixed(2)}h</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Rate: </span>
                    <span className="font-mono text-foreground">${Number(row.hourly_rate).toFixed(2)}/h</span>
                  </div>
                </div>
                <div className="flex gap-2 pt-1">
                  <Button size="sm" variant="outline" className="flex-1" onClick={() => view(row)}>
                    <FileText className="mr-1.5 h-3.5 w-3.5" /> View
                  </Button>
                  <Button size="sm" className="flex-1" onClick={() => download(row)}>
                    <Download className="mr-1.5 h-3.5 w-3.5" /> Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          );
        })
      )}
    </div>
  );
}
