import { FormEvent, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client"; import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea"; import { Badge } from "@/components/ui/badge"; import { Checkbox } from "@/components/ui/checkbox";
import { ArrowRight, Bot, CalendarPlus, Clock, Download, Mail, Phone, Plus } from "lucide-react"; import { toast } from "sonner"; import { format } from "date-fns";
import venueBanner from "@/assets/regal-venue-banner.jpg"; import type { CrmInspection, CrmInteraction, CrmLead, CrmOption, CrmTask } from "./types"; import { CRM_STAGE_VALUES, prettyCrmValue } from "./types"; import { buildBookingConfirmationPdf } from "@/lib/bookingConfirmationPdf";

export default function LeadDetailDialog({ lead, open, onOpenChange, options, interactions, inspections, tasks, menuItems, booking, businessName, onSaved }:{ lead:CrmLead|null; open:boolean; onOpenChange:(v:boolean)=>void; options:CrmOption[]; interactions:CrmInteraction[]; inspections:CrmInspection[]; tasks:CrmTask[]; menuItems:any[]; booking:any; businessName:string; onSaved:()=>void }) {
  const { user } = useAuth(); const [busy,setBusy]=useState(false); const [ai,setAi]=useState<any>(null); const [selectedMenu,setSelectedMenu]=useState<string[]>([]); const [customItems,setCustomItems]=useState<{key:string;name:string;pricePerHead:number;flatPrice:number}[]>([]); const [guestOverride,setGuestOverride]=useState<number|null>(null);
  const venueOptions=options.filter(o=>o.option_type==="venue_space"&&o.active); const leadInteractions=interactions.filter(i=>i.lead_id===lead?.id); const leadInspections=inspections.filter(i=>i.lead_id===lead?.id); const leadTasks=tasks.filter(i=>i.lead_id===lead?.id);
  const guests=guestOverride??Number(lead?.estimated_guest_count||1);
  const chosenItems=useMemo(()=>menuItems.filter(i=>selectedMenu.includes(i.id)),[menuItems,selectedMenu]);
  const lineTotal=(pph:number,flat:number)=>Number(flat||0)+Number(pph||0)*guests;
  const total=useMemo(()=>chosenItems.reduce((sum,i)=>sum+lineTotal(Number(i.price_per_head||0),Number(i.flat_price||0)),0)+customItems.reduce((sum,i)=>sum+lineTotal(i.pricePerHead,i.flatPrice),0),[chosenItems,customItems,guests]);
  const groupedMenu=useMemo(()=>{const map=new Map<string,any[]>();menuItems.forEach(i=>{const key=i.category||"Other";map.set(key,[...(map.get(key)||[]),i]);});return Array.from(map.entries());},[menuItems]);
  if(!lead)return null;
  const addInteraction=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const notes=String(f.get("notes"));const {error}=await supabase.from("crm_interactions").insert({business_id:lead.business_id,lead_id:lead.id,interaction_type:String(f.get("type")),notes,duration_minutes:f.get("duration")?Number(f.get("duration")):null,follow_up_required:f.get("follow_up")==="on",follow_up_at:f.get("follow_up_at")?String(f.get("follow_up_at")):null,shareable_feedback:f.get("shareable")==="on",logged_by:user?.id} as any);setBusy(false);if(error)toast.error(error.message);else{toast.success("Interaction logged");(e.target as HTMLFormElement).reset();onSaved();}};
  const analyse=async(notes:string)=>{if(notes.trim().length<10){toast.error("Add more notes first");return;}setBusy(true);const{data,error}=await supabase.functions.invoke("crm-ai-notes",{body:{businessId:lead.business_id,notes}});setBusy(false);if(error)toast.error("Could not analyse notes");else setAi(data);};
  const addInspection=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const start=String(f.get("starts_at"));const end=String(f.get("ends_at"));const venue=String(f.get("venue_space"));const conflict=inspections.find(i=>i.venue_space===venue&&i.status!=="cancelled"&&i.starts_at&&i.ends_at&&start<i.ends_at&&end>i.starts_at);if(conflict&&!confirm("This overlaps another inspection in the same venue. Save anyway?"))return;const{error}=await supabase.from("crm_inspections").insert({business_id:lead.business_id,lead_id:lead.id,starts_at:start,ends_at:end,status:"confirmed",venue_space:venue,pre_notes:f.get("notes")?String(f.get("notes")):null,assigned_to:user?.id,created_by:user?.id} as any);if(error)toast.error(error.message);else{await supabase.from("crm_leads").update({status:"inspection_booked"}).eq("id",lead.id);toast.success("Inspection booked");onSaved();}};
  const saveMenu=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const{data:selection,error}=await supabase.from("crm_menu_selections").upsert({business_id:lead.business_id,lead_id:lead.id,guest_count:guests,dietary_requirements:f.get("dietary")?String(f.get("dietary")):null,allergies:f.get("allergies")?String(f.get("allergies")):null,beverage_package:f.get("beverage")?String(f.get("beverage")):null,total_estimate:total,updated_by:user?.id} as any,{onConflict:"lead_id"}).select("id").single();if(error||!selection){toast.error(error?.message||"Could not save menu");return;}await supabase.from("crm_menu_selection_items").delete().eq("selection_id",selection.id);const rows=[...chosenItems.map(i=>({business_id:lead.business_id,selection_id:selection.id,menu_item_id:i.id,item_name:i.name,price_per_head:i.price_per_head,flat_price:i.flat_price})),...customItems.map(i=>({business_id:lead.business_id,selection_id:selection.id,menu_item_id:null,item_name:i.name,price_per_head:i.pricePerHead||null,flat_price:i.flatPrice||null}))];if(rows.length)await supabase.from("crm_menu_selection_items").insert(rows as any);await supabase.from("crm_leads").update({status:"menu_selected",estimated_value:total}).eq("id",lead.id);toast.success("Menu selection saved");onSaved();};
  const createBooking=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("crm_bookings").upsert({business_id:lead.business_id,lead_id:lead.id,event_date:String(f.get("event_date")),start_time:String(f.get("start_time")),duration_minutes:Number(f.get("duration")),guest_count:Number(f.get("guests")),venue_space:String(f.get("venue")),total_amount:Number(f.get("total")),deposit_amount:Number(f.get("deposit")),deposit_due_date:f.get("deposit_due")?String(f.get("deposit_due")):null,balance_due_date:f.get("balance_due")?String(f.get("balance_due")):null,created_by:user?.id,updated_by:user?.id} as any,{onConflict:"lead_id"});if(error)toast.error(error.message);else{toast.success("Booking prepared");onSaved();}};
  const downloadPdf=()=>{if(!booking)return;buildBookingConfirmationPdf({businessName,clientName:lead.full_name,eventType:prettyCrmValue(lead.event_type),eventDate:booking.event_date,eventTime:booking.start_time,durationMinutes:booking.duration_minutes,venueSpace:booking.venue_space,guestCount:booking.guest_count,menuSummary:menuItems.filter(i=>selectedMenu.includes(i.id)).map(i=>i.name),totalAmount:Number(booking.total_amount),depositAmount:Number(booking.deposit_amount),depositDueDate:booking.deposit_due_date,balanceDueDate:booking.balance_due_date}).save(`${lead.full_name.replace(/\s+/g,"-")}-booking.pdf`);};
  const setStage=async(status:string)=>{const{error}=await supabase.from("crm_leads").update({status,last_contact_at:new Date().toISOString()}).eq("id",lead.id);if(error)toast.error(error.message);else{toast.success(`Moved to ${prettyCrmValue(status)}`);onSaved();}};
  const quickLog=async(type:string)=>{setBusy(true);const{error}=await supabase.from("crm_interactions").insert({business_id:lead.business_id,lead_id:lead.id,interaction_type:type,notes:`${prettyCrmValue(type)} logged from quick actions.`,follow_up_required:false,shareable_feedback:false,logged_by:user?.id} as any);await supabase.from("crm_leads").update({last_contact_at:new Date().toISOString(),status:lead.status==="new"?"contacted":lead.status}).eq("id",lead.id);setBusy(false);if(error)toast.error(error.message);else{toast.success("Contact logged");onSaved();}};
  const quickTask=async(title:string,days:number)=>{const due=new Date(Date.now()+days*86400000).toISOString();const{error}=await supabase.from("crm_tasks").insert({business_id:lead.business_id,lead_id:lead.id,title,task_type:"follow_up",due_at:due,priority:"medium",status:"open",automated:false,created_by:user?.id} as any);if(error)toast.error(error.message);else{toast.success("Reminder added");onSaved();}};
  const nextStep=lead.status==="new"?{label:"Call the client and log the conversation",action:()=>quickLog("phone_call")}:lead.status==="contacted"?{label:"Book a venue inspection",action:null}:lead.status==="inspection_booked"?{label:"Mark the inspection as completed",action:()=>setStage("inspected")}:lead.status==="inspected"?{label:"Build the menu and pricing",action:null}:lead.status==="menu_selected"?{label:"Send the quote and mark as quoted",action:()=>setStage("quoted")}:lead.status==="quoted"?{label:"Prepare the booking and confirm",action:()=>setStage("confirmed")}:null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[94dvh] overflow-y-auto p-0 sm:max-w-5xl"><div className="relative h-44 overflow-hidden"><img src={venueBanner} alt="Warm venue interior" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-background/65"/><DialogHeader className="absolute bottom-0 left-0 p-6"><div className="flex gap-2"><Badge>{prettyCrmValue(lead.status)}</Badge>{lead.calendly_source&&<Badge variant="outline">Calendly</Badge>}</div><DialogTitle className="mt-2 font-serif text-3xl text-foreground">{lead.full_name}</DialogTitle><p className="text-sm text-foreground/80">{lead.event_type&&prettyCrmValue(lead.event_type)} · {lead.estimated_guest_count||"—"} guests</p></DialogHeader></div>
  <div className="border-b border-border bg-muted/30 px-5 py-4">
    <div className="flex flex-wrap items-center gap-2">
      <Button size="sm" variant="outline" disabled={!lead.phone} asChild={!!lead.phone}>{lead.phone?<a href={`tel:${lead.phone}`}><Phone className="mr-2 h-4 w-4"/>Call</a>:<span><Phone className="mr-2 h-4 w-4"/>Call</span>}</Button>
      <Button size="sm" variant="outline" disabled={!lead.email} asChild={!!lead.email}>{lead.email?<a href={`mailto:${lead.email}`}><Mail className="mr-2 h-4 w-4"/>Email</a>:<span><Mail className="mr-2 h-4 w-4"/>Email</span>}</Button>
      <Button size="sm" variant="outline" disabled={busy} onClick={()=>quickLog("phone_call")}><Phone className="mr-2 h-4 w-4"/>Log call</Button>
      <Button size="sm" variant="outline" onClick={()=>quickTask(`Follow up with ${lead.full_name}`,2)}><Clock className="mr-2 h-4 w-4"/>Remind me in 2 days</Button>
      <select value={lead.status} onChange={e=>setStage(e.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{CRM_STAGE_VALUES.map(s=><option key={s} value={s}>{prettyCrmValue(s)}</option>)}</select>
    </div>
    {nextStep&&<div className="mt-3 flex flex-wrap items-center gap-3 rounded-md border border-primary/30 bg-primary/5 px-3 py-2 text-sm"><ArrowRight className="h-4 w-4 text-primary"/><span>Next step: {nextStep.label}</span>{nextStep.action&&<Button size="sm" variant="secondary" onClick={nextStep.action}>Done</Button>}</div>}
  </div>
  <div className="p-5"><Tabs defaultValue="timeline"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="inspection">Inspection</TabsTrigger><TabsTrigger value="menu">Menu</TabsTrigger><TabsTrigger value="booking">Confirmation</TabsTrigger></TabsList>
  <TabsContent value="timeline" className="space-y-5"><div className="flex flex-wrap gap-3 text-sm"><span className="flex items-center gap-1"><Phone className="h-4 w-4"/>{lead.phone||"No phone"}</span><span className="flex items-center gap-1"><Mail className="h-4 w-4"/>{lead.email||"No email"}</span></div>
    <form onSubmit={addInteraction} className="grid gap-3 rounded-md border border-border p-4"><div className="grid gap-3 sm:grid-cols-3"><select name="type" className="h-10 rounded-md border border-input bg-background px-3"><option value="phone_call">Phone call</option><option value="email">Email</option><option value="in_person">In person</option><option value="message">Message</option></select><Input name="duration" type="number" min="1" placeholder="Duration (minutes)"/><Input name="follow_up_at" type="datetime-local"/></div><Textarea id="crm-note" name="notes" required placeholder="Questions, decisions and next steps"/><div className="flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm"><Checkbox name="follow_up"/> Follow-up required</label><label className="flex items-center gap-2 text-sm"><Checkbox name="shareable"/> Shareable feedback</label><Button type="button" variant="outline" size="sm" onClick={()=>analyse((document.getElementById("crm-note") as HTMLTextAreaElement)?.value||"")}><Bot className="mr-2 h-4 w-4"/>Suggest actions</Button><Button size="sm" disabled={busy}><Plus className="mr-2 h-4 w-4"/>Log interaction</Button></div></form>
    {ai&&<div className="rounded-md border border-primary/30 bg-primary/5 p-4 text-sm"><p className="font-semibold">AI suggestion</p><p className="mt-1">{ai.summary}</p>{ai.tasks?.map((task:any,index:number)=><p key={index} className="mt-1 text-muted-foreground">• {task.title}{task.suggested_date?` — ${task.suggested_date}`:""}</p>)}</div>}
    <div className="space-y-3">{leadInteractions.map(i=><div key={i.id} className="border-l-2 border-primary/40 pl-4"><div className="flex justify-between gap-3"><p className="font-medium">{prettyCrmValue(i.interaction_type)}</p><time className="text-xs text-muted-foreground">{format(new Date(i.occurred_at),"dd/MM/yyyy h:mm a")}</time></div><p className="mt-1 text-sm text-muted-foreground">{i.notes}</p></div>)}</div>
  </TabsContent>
  <TabsContent value="inspection" className="space-y-4"><form onSubmit={addInspection} className="grid gap-3 sm:grid-cols-2"><div><Label>Starts</Label><Input name="starts_at" type="datetime-local" required/></div><div><Label>Ends</Label><Input name="ends_at" type="datetime-local" required/></div><div><Label>Venue space</Label><select name="venue_space" required className="h-10 w-full rounded-md border border-input bg-background px-3">{venueOptions.map(o=><option key={o.id} value={o.value}>{o.label}</option>)}</select></div><div><Label>Pre-inspection notes</Label><Input name="notes"/></div><Button className="sm:col-span-2"><CalendarPlus className="mr-2 h-4 w-4"/>Book inspection</Button></form>{leadInspections.map(i=><div key={i.id} className="rounded-md border p-4"><div className="flex justify-between"><p className="font-medium">{i.venue_space}</p><Badge variant="outline">{prettyCrmValue(i.status)}</Badge></div><p className="text-sm text-muted-foreground">{i.starts_at?format(new Date(i.starts_at),"dd/MM/yyyy h:mm a"):"Proposed"}</p></div>)}</TabsContent>
  <TabsContent value="menu"><form onSubmit={saveMenu} className="space-y-5"><div className="grid gap-3 sm:grid-cols-2">{menuItems.map(item=><label key={item.id} className="flex items-start gap-3 rounded-md border p-3"><Checkbox checked={selectedMenu.includes(item.id)} onCheckedChange={(checked)=>setSelectedMenu(v=>checked?[...v,item.id]:v.filter(id=>id!==item.id))}/><span><span className="font-medium">{item.name}</span><span className="block text-xs text-muted-foreground">{item.description||item.category} · {item.price_per_head?`$${item.price_per_head}/guest`:`$${item.flat_price||0}`}</span></span></label>)}</div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Dietary requirements</Label><Textarea name="dietary"/></div><div><Label>Allergies</Label><Textarea name="allergies" className="border-destructive/40"/></div></div><div className="flex items-center justify-between"><p className="font-serif text-2xl">Estimated total: ${total.toFixed(2)}</p><Button>Save menu</Button></div></form></TabsContent>
  <TabsContent value="booking"><form onSubmit={createBooking} className="grid gap-3 sm:grid-cols-2"><div><Label>Event date</Label><Input name="event_date" type="date" required defaultValue={booking?.event_date||lead.preferred_dates?.[0]}/></div><div><Label>Start time</Label><Input name="start_time" type="time" required defaultValue={booking?.start_time}/></div><div><Label>Duration (minutes)</Label><Input name="duration" type="number" min="30" required defaultValue={booking?.duration_minutes||300}/></div><div><Label>Confirmed guests</Label><Input name="guests" type="number" min="1" required defaultValue={booking?.guest_count||lead.estimated_guest_count||1}/></div><div><Label>Venue</Label><select name="venue" className="h-10 w-full rounded-md border border-input bg-background px-3" defaultValue={booking?.venue_space||lead.venue_space||""}>{venueOptions.map(o=><option key={o.id} value={o.value}>{o.label}</option>)}</select></div><div><Label>Total</Label><Input name="total" type="number" min="0" defaultValue={booking?.total_amount||total}/></div><div><Label>Deposit</Label><Input name="deposit" type="number" min="0" defaultValue={booking?.deposit_amount||0}/></div><div><Label>Deposit due</Label><Input name="deposit_due" type="date" defaultValue={booking?.deposit_due_date}/></div><div><Label>Balance due</Label><Input name="balance_due" type="date" defaultValue={booking?.balance_due_date}/></div><div className="flex flex-wrap gap-2 self-end"><Button>{booking?"Update booking":"Prepare booking"}</Button>{booking&&<Button type="button" variant="outline" onClick={downloadPdf}><Download className="mr-2 h-4 w-4"/>PDF</Button>}{booking&&<Button type="button" variant="outline" onClick={()=>setStage("confirmed")}>Mark confirmed</Button>}</div></form><div className="mt-5 space-y-2">{leadTasks.map(t=><p key={t.id} className="text-sm text-muted-foreground">• {t.title}</p>)}</div></TabsContent>
  </Tabs></div></DialogContent></Dialog>;
}