// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthed = () => ({
  content: [{ type: "text", text: "Not authenticated" }],
  isError: true
});

// src/lib/mcp/tools/list-businesses.ts
var list_businesses_default = defineTool({
  name: "list_businesses",
  title: "List businesses",
  description: "List the businesses you can access, with their IDs and codes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("businesses").select("id, name, code").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const businesses = (data ?? []).map((b) => ({ id: String(b.id), name: String(b.name ?? ""), code: String(b.code ?? "") }));
    return { content: [{ type: "text", text: JSON.stringify(businesses) }], structuredContent: { businesses } };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "List sales leads",
  description: "List recent sales leads for a business, optionally filtered by pipeline stage.",
  inputSchema: {
    business_id: z.string().uuid().describe("Business ID from list_businesses."),
    status: z.string().optional().describe("Pipeline stage, e.g. new, contacted, inspection_booked, deposit_received, cold."),
    limit: z.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    let q = supabaseForUser(ctx).from("crm_leads").select("id, full_name, email, phone, company, event_type, lead_kind, status, estimated_guest_count, preferred_dates, created_at").eq("business_id", business_id).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const leads = (data ?? []).map((l) => ({
      id: l.id,
      name: l.full_name,
      email: l.email,
      phone: l.phone,
      company: l.company,
      event_type: l.event_type,
      kind: l.lead_kind,
      status: l.status,
      guests: l.estimated_guest_count,
      preferred_dates: [...l.preferred_dates ?? []],
      created_at: l.created_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(leads) }], structuredContent: { leads } };
  }
});

// src/lib/mcp/tools/list-upcoming-bookings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_bookings_default = defineTool3({
  name: "list_upcoming_bookings",
  title: "List upcoming events",
  description: "List upcoming event and catering bookings for a business from today onward.",
  inputSchema: {
    business_id: z2.string().uuid().describe("Business ID from list_businesses."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const today = (/* @__PURE__ */ new Date()).toLocaleDateString("en-CA", { timeZone: "Australia/Sydney" });
    const { data, error } = await supabaseForUser(ctx).from("crm_bookings").select("id, event_name, event_type, booking_kind, event_date, start_time, end_time, guest_count, status, service_location").eq("business_id", business_id).gte("event_date", today).order("event_date").limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bookings = (data ?? []).map((b) => ({
      id: b.id,
      name: b.event_name,
      type: b.event_type,
      kind: b.booking_kind,
      date: b.event_date,
      start_time: b.start_time,
      end_time: b.end_time,
      guests: b.guest_count,
      status: b.status,
      location: b.service_location
    }));
    return { content: [{ type: "text", text: JSON.stringify(bookings) }], structuredContent: { bookings } };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool4({
  name: "list_open_tasks",
  title: "List open tasks",
  description: "List open sales & events tasks for a business, soonest due first.",
  inputSchema: {
    business_id: z3.string().uuid().describe("Business ID from list_businesses."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("crm_tasks").select("id, title, description, due_at, priority, status, lead_id").eq("business_id", business_id).eq("status", "open").order("due_at").limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const tasks = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      due_at: t.due_at,
      priority: t.priority,
      lead_id: t.lead_id
    }));
    return { content: [{ type: "text", text: JSON.stringify(tasks) }], structuredContent: { tasks } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Add a manual sales & events task for a business, optionally linked to a lead.",
  inputSchema: {
    business_id: z4.string().uuid().describe("Business ID from list_businesses."),
    title: z4.string().trim().min(1).describe("Task title."),
    due_at: z4.string().describe("Due date/time as ISO 8601, e.g. 2026-10-01T10:00:00+10:00."),
    priority: z4.enum(["low", "medium", "high"]).optional().describe("Defaults to medium."),
    description: z4.string().optional().describe("Optional notes."),
    lead_id: z4.string().uuid().optional().describe("Optional linked lead ID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ business_id, title, due_at, priority, description, lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const userId = ctx.getUserId();
    const { data, error } = await supabaseForUser(ctx).from("crm_tasks").insert({
      business_id,
      title,
      due_at,
      priority: priority ?? "medium",
      description: description ?? null,
      lead_id: lead_id ?? null,
      task_type: "manual",
      status: "open",
      automated: false,
      assigned_to: userId,
      created_by: userId
    }).select("id, title, due_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const task = { id: data.id, title: data.title, due_at: data.due_at };
    return { content: [{ type: "text", text: `Created task "${task.title}"` }], structuredContent: { task } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fhotpjcgoyuqyhttawef";
var mcp_default = defineMcp({
  name: "omnexclock",
  title: "OmnexClock",
  version: "0.1.0",
  instructions: "Tools for Regal Clock sales & events. Call list_businesses first to get a business_id, then list leads, upcoming bookings, open tasks, or create a task.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_businesses_default, list_leads_default, list_upcoming_bookings_default, list_tasks_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
