import { FormEvent, useMemo, useState } from "react";
import { useAuth } from "@/contexts/AuthContext"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Badge } from "@/components/ui/badge"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Switch } from "@/components/ui/switch"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertTriangle, CalendarDays, Check, ChevronRight, ClipboardList, Download, ExternalLink, LayoutDashboard, ListFilter, Mail, Phone, Plus, Search, Settings, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client"; import { toast } from "sonner"; import { format, isAfter, startOfDay, subDays } from "date-fns";
import { useCrmData } from "@/features/sales/useCrmData"; import LeadFormDialog from "@/features/sales/LeadFormDialog"; import LeadDetailDialog from "@/features/sales/LeadDetailDialog"; import type { CrmLead } from "@/features/sales/types"; import { CRM_STAGE_VALUES, prettyCrmValue } from "@/features/sales/types";

const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
export default function SalesMarketingPage(){
  const {business,leads,options,inspections,tasks,interactions,settings,bookings,menuItems,loading,refresh}=useCrmData(); const {isAdminOf,isSuperAdminOf}=useAuth();
  const [search,setSearch]=useState(""); const [stageFilter,setStageFilter]=useState("all"); const [leadOpen,setLeadOpen]=useState(false); const [editing,setEditing]=useState<CrmLead|null>(null); const [detail,setDetail]=useState<CrmLead|null>(null); const [dragged,setDragged]=useState<string|null>(null);
  const filtered=useMemo(()=>leads.filter(l=>(stageFilter==="all"||l.status===stageFilter)&&`${l.full_name} ${l.email||""} ${l.phone||""} ${l.company||""}`.toLowerCase().includes(search.toLowerCase())),[leads,search,stageFilter]);
  const staleDays=settings?.stale_days||5; const isStale=(lead:CrmLead)=>!['confirmed','lost'].includes(lead.status)&&!isAfter(new Date(lead.last_contact_at||lead.created_at),subDays(new Date(),staleDays));
  const updateStage=async(id:string,status:string)=>{await supabase.from("crm_leads").update({status,lost_reason:status==="lost"?"other":null}).eq("id",id);setDragged(null);refresh();};
  const exportCsv=()=>{const quote=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const rows=[["Name","Phone","Email","Source","Event type","Preferred date","Guests","Status","Value"],...filtered.map(l=>[l.full_name,l.phone,l.email,prettyCrmValue(l.source),prettyCrmValue(l.event_type),l.preferred_dates?.[0],l.estimated_guest_count,prettyCrmValue(l.status),l.estimated_value])];const blob=new Blob([rows.map(r=>r.map(quote).join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${business?.business_code||"Business"}__Sales-Marketing-Leads__${format(new Date(),"dd.MM.yyyy")}.csv`;a.click();URL.revokeObjectURL(a.href);};
  const today=tasks.filter(t=>t.status==="open"&&new Date(t.due_at)<=new Date(Date.now()+86400000)); const upcoming=inspections.filter(i=>i.starts_at&&new Date(i.starts_at)>=startOfDay(new Date())&&i.status!=="cancelled").slice(0,6); const confirmed=leads.filter(l=>l.status==="confirmed").length; const active=leads.filter(l=>!['confirmed','lost'].includes(l.status)); const pipelineValue=active.reduce((s,l)=>s+Number(l.estimated_value),0); const shareable=interactions.find(i=>i.shareable_feedback);
  const sourceStats=Object.entries(leads.reduce<Record<string,number>>((acc,l)=>({...acc,[l.source]:(acc[l.source]||0)+1}),{})).sort((a,b)=>b[1]-a[1]);
  const completeTask=async(id:string)=>{await supabase.from("crm_tasks").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",id);refresh();};
  if(!business)return null;
  const canConfigure=isAdminOf(business.id)||isSuperAdminOf(business.id);
  const NavIcon=({name}:{name:string})=>name==="dashboard"?<LayoutDashboard className="h-4 w-4"/>:name==="leads"?<Users className="h-4 w-4"/>:name==="pipeline"?<ListFilter className="h-4 w-4"/>:name==="inspections"?<CalendarDays className="h-4 w-4"/>:name==="tasks"?<ClipboardList className="h-4 w-4"/>:<Settings className="h-4 w-4"/>;
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase text-primary">{business.name}</p><h1 className="font-serif text-3xl font-semibold sm:text-4xl">Sales & Marketing</h1><p className="mt-1 text-sm text-muted-foreground">Leads, inspections, menus and confirmed events.</p></div><div className="flex gap-2"><Button variant="outline" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button onClick={()=>{setEditing(null);setLeadOpen(true)}}><Plus className="mr-2 h-4 w-4"/>New lead</Button></div></div>
    <Tabs defaultValue="dashboard"><TabsList className="h-auto w-full justify-start overflow-x-auto bg-transparent p-0">{["dashboard","leads","pipeline","inspections","tasks","settings"].map(tab=><TabsTrigger key={tab} value={tab} className="gap-2 border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:shadow-none"><NavIcon name={tab}/>{prettyCrmValue(tab)}</TabsTrigger>)}</TabsList>
      <TabsContent value="dashboard" className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active leads",active.length],["Pipeline value",money(pipelineValue)],["Confirmed",confirmed],["Conversion",`${leads.length?Math.round(confirmed/leads.length*100):0}%`]].map(([label,value])=><Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p></CardContent></Card>)}</div>
        <div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Lead sources</CardTitle></CardHeader><CardContent className="space-y-4">{sourceStats.length?sourceStats.map(([source,count])=><div key={source}><div className="mb-1 flex justify-between text-sm"><span>{prettyCrmValue(source)}</span><span>{count}</span></div><div className="h-2 bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${count/Math.max(leads.length,1)*100}%`}}/></div></div>):<p className="text-sm text-muted-foreground">No leads yet.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Recent client feedback</CardTitle></CardHeader><CardContent>{shareable?<blockquote className="font-serif text-lg leading-relaxed">“{shareable.notes}”</blockquote>:<p className="text-sm text-muted-foreground">Flag a client note as shareable to feature it here.</p>}</CardContent></Card></div>
        <div className="grid gap-6 lg:grid-cols-3"><Card><CardHeader><CardTitle>Today’s tasks</CardTitle></CardHeader><CardContent className="space-y-3">{today.length?today.map(t=><div key={t.id} className="flex items-center justify-between gap-3 border-b border-border pb-3"><div><p className="text-sm font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{format(new Date(t.due_at),"dd/MM/yyyy h:mm a")}</p></div><Button size="icon" variant="ghost" title="Complete task" onClick={()=>completeTask(t.id)}><Check className="h-4 w-4"/></Button></div>):<p className="text-sm text-muted-foreground">Nothing due today.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-destructive"/>Needs attention</CardTitle></CardHeader><CardContent className="space-y-3">{active.filter(isStale).length?active.filter(isStale).slice(0,6).map(l=><button key={l.id} onClick={()=>setDetail(l)} className="flex w-full items-center justify-between border-b border-border pb-3 text-left text-sm hover:text-primary"><span>{l.full_name}</span><span className="text-xs text-muted-foreground">{prettyCrmValue(l.status)}</span></button>):<p className="text-sm text-muted-foreground">Every active lead has been contacted recently.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Upcoming inspections</CardTitle></CardHeader><CardContent className="space-y-3">{upcoming.length?upcoming.map(i=><div key={i.id} className="flex justify-between border-b border-border pb-3 text-sm"><span>{i.venue_space}</span><span className="text-muted-foreground">{format(new Date(i.starts_at as string),"dd/MM h:mm a")}</span></div>):<p className="text-sm text-muted-foreground">No inspections scheduled.</p>}</CardContent></Card></div>
      </TabsContent>
      <TabsContent value="leads"><div className="mb-4 space-y-3"><div className="flex items-center gap-2"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads"/></div></div><div className="flex flex-wrap gap-2">{["all",...CRM_STAGE_VALUES].map(stage=><Button key={stage} size="sm" variant={stageFilter===stage?"default":"outline"} onClick={()=>setStageFilter(stage)}>{stage==="all"?`All (${leads.length})`:`${prettyCrmValue(stage)} (${leads.filter(l=>l.status===stage).length})`}</Button>)}</div></div><div className="overflow-x-auto rounded-md border"><table className="w-full text-left text-sm"><thead className="bg-muted/60"><tr><th className="p-3">Lead</th><th className="p-3">Event</th><th className="p-3">Date</th><th className="p-3">Guests</th><th className="p-3">Stage</th><th className="p-3">Value</th><th/></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="border-t border-border hover:bg-muted/30"><td className="p-3"><button className="font-medium hover:text-primary" onClick={()=>setDetail(l)}>{l.full_name}</button><p className="text-xs text-muted-foreground">{l.email||l.phone||"No contact details"}</p></td><td className="p-3">{prettyCrmValue(l.event_type)}</td><td className="p-3">{l.preferred_dates?.[0]||"Flexible"}</td><td className="p-3">{l.estimated_guest_count||"—"}</td><td className="p-3"><Badge variant={isStale(l)?"destructive":"outline"}>{isStale(l)?"Stale":prettyCrmValue(l.status)}</Badge></td><td className="p-3">{money(Number(l.estimated_value))}</td><td className="p-3"><div className="flex justify-end gap-1">{l.phone&&<Button size="icon" variant="ghost" title="Call lead" asChild><a href={`tel:${l.phone}`}><Phone className="h-4 w-4"/></a></Button>}{l.email&&<Button size="icon" variant="ghost" title="Email lead" asChild><a href={`mailto:${l.email}`}><Mail className="h-4 w-4"/></a></Button>}<Button size="icon" variant="ghost" title="Open lead" onClick={()=>setDetail(l)}><ChevronRight className="h-4 w-4"/></Button></div></td></tr>)}</tbody></table></div></TabsContent>
      <TabsContent value="pipeline"><div className="overflow-x-auto pb-4"><div className="grid min-w-[1700px] grid-cols-8 gap-3">{CRM_STAGE_VALUES.map(stage=><section key={stage} onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&updateStage(dragged,stage)} className="min-h-[420px] rounded-md border border-border bg-muted/20 p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">{prettyCrmValue(stage)}</h2><Badge variant="outline">{leads.filter(l=>l.status===stage).length}</Badge></div><div className="space-y-3">{leads.filter(l=>l.status===stage).map(l=><Card key={l.id} draggable onDragStart={()=>setDragged(l.id)} className="cursor-grab active:cursor-grabbing"><CardContent className="p-3"><button className="text-left font-medium hover:text-primary" onClick={()=>setDetail(l)}>{l.full_name}</button><p className="mt-1 text-xs text-muted-foreground">{prettyCrmValue(l.event_type)} · {l.estimated_guest_count||"—"}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs text-primary">{money(Number(l.estimated_value))}</span>{isStale(l)&&<Badge variant="destructive" className="text-[10px]">Stale</Badge>}</div></CardContent></Card>)}</div></section>)}</div></div></TabsContent>
      <TabsContent value="inspections"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{inspections.map(i=>{const lead=leads.find(l=>l.id===i.lead_id);return <Card key={i.id}><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="font-serif text-xl">{lead?.full_name||"Lead"}</p><p className="text-sm text-primary">{i.venue_space}</p></div><Badge variant="outline">{prettyCrmValue(i.status)}</Badge></div><p className="mt-4 text-sm">{i.starts_at?format(new Date(i.starts_at),"EEEE, dd/MM/yyyy · h:mm a"):"Proposed time"}</p>{i.calendly_source&&<p className="mt-2 text-xs text-muted-foreground">Source: Calendly</p>}</CardContent></Card>})}</div></TabsContent>
      <TabsContent value="tasks"><Card><CardContent className="p-0"><div className="divide-y divide-border">{tasks.map(t=><div key={t.id} className="flex items-center gap-3 p-4"><Button size="icon" variant={t.status==="completed"?"secondary":"outline"} title="Complete task" onClick={()=>completeTask(t.id)}><Check className="h-4 w-4"/></Button><div className="min-w-0 flex-1"><p className={t.status==="completed"?"line-through text-muted-foreground":"font-medium"}>{t.title}</p><p className="text-xs text-muted-foreground">Due {format(new Date(t.due_at),"dd/MM/yyyy h:mm a")} · {prettyCrmValue(t.priority)}</p></div>{t.automated&&<Badge variant="outline">Automated</Badge>}</div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="settings"><SettingsPanel businessId={business.id} businessCode={business.business_code} options={options} settings={settings} menuItems={menuItems} canConfigure={canConfigure} refresh={refresh}/></TabsContent>
    </Tabs>
    <LeadFormDialog open={leadOpen} onOpenChange={setLeadOpen} businessId={business.id} options={options} lead={editing} leads={leads} onSaved={refresh}/>
    <LeadDetailDialog lead={detail} open={!!detail} onOpenChange={o=>!o&&setDetail(null)} options={options} interactions={interactions} inspections={inspections} tasks={tasks} menuItems={menuItems} booking={bookings.find(b=>b.lead_id===detail?.id)} businessName={business.name} onSaved={refresh}/>
  </div>;
}

function SettingsPanel({businessId,businessCode,options,settings,menuItems,canConfigure,refresh}:{businessId:string;businessCode:string;options:any[];settings:any;menuItems:any[];canConfigure:boolean;refresh:()=>void}){
  const saveSettings=async(values:any)=>{const{error}=await supabase.from("crm_settings").update(values).eq("business_id",businessId);if(error)toast.error(error.message);else{toast.success("Settings saved");refresh();}};
  const addOption=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const label=String(f.get("label"));const value=label.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");const{error}=await supabase.from("crm_options").insert({business_id:businessId,option_type:f.get("type") as string,label,value,sort_order:options.filter(o=>o.option_type===f.get("type")).length});if(error)toast.error(error.message);else{(e.target as HTMLFormElement).reset();refresh();}};
  const addMenu=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("crm_menu_items").insert({business_id:businessId,name:String(f.get("name")),category:String(f.get("category")),price_per_head:f.get("price")?Number(f.get("price")):null,flat_price:f.get("flat")?Number(f.get("flat")):null,description:f.get("description")?String(f.get("description")):null} as any);if(error)toast.error(error.message);else{(e.target as HTMLFormElement).reset();toast.success("Menu item added");refresh();}};
  return <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Lead automation</CardTitle></CardHeader><CardContent className="space-y-5"><div><Label>Stale lead threshold (days)</Label><Input type="number" min="1" defaultValue={settings?.stale_days||5} disabled={!canConfigure} onBlur={e=>saveSettings({stale_days:Number(e.target.value)})}/></div><div className="flex items-center justify-between"><div><p className="font-medium">Calendly integration</p><p className="text-sm text-muted-foreground">Optional and disabled until a business administrator connects it.</p></div><Switch checked={!!settings?.calendly_enabled} disabled/></div><Button variant="outline" disabled><ExternalLink className="mr-2 h-4 w-4"/>Connect Calendly</Button><p className="text-xs text-muted-foreground">Calendly’s client-facing booking page remains unchanged. Connection authorization will be requested separately for each business.</p><div><Label>Public enquiry page</Label><div className="mt-1 flex gap-2"><Input readOnly value={`${window.location.origin}/b/${businessCode}/enquire`}/><Button variant="outline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/b/${businessCode}/enquire`)}>Copy</Button></div></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Configurable lists</CardTitle></CardHeader><CardContent className="space-y-4">{canConfigure&&<form onSubmit={addOption} className="flex gap-2"><select name="type" className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="lead_source">Lead source</option><option value="event_type">Event type</option><option value="lost_reason">Lost reason</option><option value="venue_space">Venue space</option><option value="beverage_package">Beverage package</option><option value="live_stall">Live stall</option></select><Input name="label" required placeholder="New option"/><Button size="icon" title="Add option"><Plus className="h-4 w-4"/></Button></form>}<div className="flex max-h-72 flex-wrap content-start gap-2 overflow-y-auto">{options.map(o=><Badge key={o.id} variant="outline">{o.label}</Badge>)}</div></CardContent></Card>
    <Card className="lg:col-span-2"><CardHeader><CardTitle>Menu catalogue</CardTitle></CardHeader><CardContent>{canConfigure&&<form onSubmit={addMenu} className="grid gap-2 sm:grid-cols-5"><Input name="name" required placeholder="Package or add-on"/><select name="category" defaultValue="nepali_catering" className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="nepali_express">Nepali Express</option><option value="nepali_catering">Nepali Catering Packages</option><option value="indian_catering">Indian Catering Packages</option><option value="live_stall">Live Stall</option><option value="beverage">Beverage</option><option value="addon">Add-on</option><option value="custom">Custom</option></select><Input name="price" type="number" min="0" step="0.01" placeholder="Price per guest"/><Input name="flat" type="number" min="0" step="0.01" placeholder="Flat price"/><Button>Add menu item</Button><Input name="description" className="sm:col-span-5" placeholder="Description and dietary notes"/></form>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{menuItems.map(item=><div key={item.id} className="rounded-md border p-3"><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{MENU_CATEGORY_LABELS[item.category as string]||item.category}</p><p className="mt-2 text-sm text-primary">{item.price_per_head?`$${item.price_per_head} per guest`:`$${item.flat_price||0}`}</p></div>)}</div></CardContent></Card>
  </div>;
}